server:
  port: ${APP_PORT}
spring:
  cloud:
    gateway:
      routes:
        - id: dadata
          uri: http://${DADATA_HOST}:${DADATA_PORT}/
          predicates:
            - Path=/dadata/**
        - id: not-dadata
          uri: http://${NOT_DADATA_HOST}:${NOT_DADATA_PORT}/
          predicates:
            - Path=/not-dadata/**
        - id: consul
          uri: http://${CONSUL_HOST}:${CONSUL_PORT}/
          predicates:
            - Path=/**