server:
  port: ${APP_PORT}
spring:
  application:
    name: kladr-services
  cloud:
    consul:
      discovery:
        instance-id: dadata
        health-check-url: http://${APP_HOST}:${APP_PORT}/dadata/
        hostname: ${DISCOVERY_HOST}
        port: ${DISCOVERY_PORT}
key:
  api: ${API_KEY}
  secret: ${SECRET_KEY}