server:
  port: ${APP_PORT}
spring:
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: dadata
        serviceName: kladr-services
        health-check-url: http://${APP_HOST}:${APP_PORT}/dadata/
key:
  api: ${API_KEY}
  secret: ${SECRET_KEY}