server:
  port: 8081
spring:
  application:
    name: kladr-services
  cloud:
    consul:
      discovery:
        instance-id: dadata
        health-check-url: http://localhost:8081/
        hostname: localhost
        port: 8500