server:
  port: 8081
spring:
  application:
    name: kladr-services
  cloud:
    consul:
      discovery:
        instance-id: dadata
        health-check-url: http://localhost:8081/dadata/
        hostname: localhost
        port: 8500
key:
  api: ${API_KEY}
  secret: ${SECRET_KEY}