server:
  port: 8082
spring:
  application:
    name: kladr-services
  cloud:
    consul:
      discovery:
        instance-id: not-dadata
        health-check-url: http://localhost:8082/
        hostname: localhost
        port: 8500