server:
  port: ${APP_PORT}
spring:
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: not-dadata
        serviceName: kladr-services
        health-check-url: http://${APP_HOST}:${APP_PORT}/not-dadata/
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}