server:
  port: ${APP_PORT}
spring:
  application:
    name: kladr-services
  cloud:
    consul:
      discovery:
        instance-id: not-dadata
        health-check-url: http://${APP_HOST}:${APP_PORT}/not-dadata/
        hostname: ${DISCOVERY_HOST}
        port: ${DISCOVERY_PORT}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}